"""create surf_sessions table

Revision ID: 0f0fb3f4fcea
Revises: 9561d6a3b591
Create Date: 2026-01-12 11:58:02.444269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f0fb3f4fcea'
down_revision: Union[str, Sequence[str], None] = '9561d6a3b591'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surf_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('spot', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('wave_quality', sa.Integer(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surf_sessions_id'), 'surf_sessions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_surf_sessions_id'), table_name='surf_sessions')
    op.drop_table('surf_sessions')
    # ### end Alembic commands ###
