"""add spots table and refactor sessions

Revision ID: 1190b997a895
Revises: 4ebf2c12b7a9
Create Date: 2026-01-21 14:28:54.179357

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1190b997a895'
down_revision: Union[str, Sequence[str], None] = '4ebf2c12b7a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    spot_difficulty_enum = postgresql.ENUM(
        "beginner",
        "intermediate",
        "advanced",
        "expert",
        name="spot_difficulty",
        create_type=False,
    )
    spot_difficulty_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('spots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('difficulty', postgresql.ARRAY(spot_difficulty_enum), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spots_name'), 'spots', ['name'], unique=True)
    op.create_check_constraint(
        "ck_spots_difficulty_adjacent",
        "spots",
        """
        difficulty IS NULL OR
        difficulty = ARRAY['beginner']::spot_difficulty[] OR
        difficulty = ARRAY['intermediate']::spot_difficulty[] OR
        difficulty = ARRAY['advanced']::spot_difficulty[] OR
        difficulty = ARRAY['expert']::spot_difficulty[] OR
        difficulty = ARRAY['beginner','intermediate']::spot_difficulty[] OR
        difficulty = ARRAY['intermediate','advanced']::spot_difficulty[] OR
        difficulty = ARRAY['advanced','expert']::spot_difficulty[] OR
        difficulty = ARRAY['beginner','intermediate','advanced']::spot_difficulty[] OR
        difficulty = ARRAY['intermediate','advanced','expert']::spot_difficulty[]
        """,
    )
    op.add_column('surf_sessions', sa.Column('spot_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surf_sessions', 'spots', ['spot_id'], ['id'])

    # Backfill spots from existing surf_sessions.spot strings.
    op.execute(
        """
        INSERT INTO spots (name)
        SELECT DISTINCT spot
        FROM surf_sessions
        WHERE spot IS NOT NULL
        ON CONFLICT (name) DO NOTHING
        """
    )
    op.execute(
        """
        UPDATE surf_sessions s
        SET spot_id = sp.id
        FROM spots sp
        WHERE s.spot IS NOT NULL AND sp.name = s.spot
        """
    )

    op.drop_column("surf_sessions", "spot")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    spot_difficulty_enum = postgresql.ENUM(
        "beginner",
        "intermediate",
        "advanced",
        "expert",
        name="spot_difficulty",
        create_type=False,
    )

    op.add_column("surf_sessions", sa.Column("spot", sa.VARCHAR(), autoincrement=False, nullable=True))
    op.execute(
        """
        UPDATE surf_sessions s
        SET spot = sp.name
        FROM spots sp
        WHERE s.spot_id = sp.id
        """
    )
    op.drop_constraint(None, 'surf_sessions', type_='foreignkey')
    op.drop_column('surf_sessions', 'spot_id')
    op.drop_constraint("ck_spots_difficulty_adjacent", "spots", type_="check")
    op.drop_index(op.f('ix_spots_name'), table_name='spots')
    op.drop_table('spots')
    spot_difficulty_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
