"""add tide columns to surf_sessions

Revision ID: 1a32e2973cc7
Revises: b3e1faeefc05
Create Date: 2026-02-04 16:19:39.956541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a32e2973cc7'
down_revision: Union[str, Sequence[str], None] = 'b3e1faeefc05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_sessions', sa.Column('tide_height_m', sa.Float(), nullable=True))
    op.add_column('surf_sessions', sa.Column('tide_low_m', sa.Float(), nullable=True))
    op.add_column('surf_sessions', sa.Column('tide_high_m', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_sessions', 'tide_high_m')
    op.drop_column('surf_sessions', 'tide_low_m')
    op.drop_column('surf_sessions', 'tide_height_m')
    # ### end Alembic commands ###
