"""update surf_sessions table

Revision ID: 406a934ab054
Revises: 0f0fb3f4fcea
Create Date: 2026-01-12 13:01:30.474410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '406a934ab054'
down_revision: Union[str, Sequence[str], None] = '0f0fb3f4fcea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_sessions', sa.Column('user_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_sessions', 'user_id')
    # ### end Alembic commands ###
