"""updated SurfForecast table

Revision ID: 780920bd1444
Revises: 85cd77af170c
Create Date: 2026-01-31 19:25:25.598161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780920bd1444'
down_revision: Union[str, Sequence[str], None] = '85cd77af170c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_forecasts', 'is_partial')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_forecasts', sa.Column('is_partial', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
