"""update sessions table

Revision ID: 831bd530d0b7
Revises: 406a934ab054
Create Date: 2026-01-12 21:02:56.270646

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '831bd530d0b7'
down_revision: Union[str, Sequence[str], None] = '406a934ab054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "surf_sessions",
        "created_at",
        existing_type=sa.DateTime(),
        server_default=sa.text("now()"),
        existing_nullable=False,
)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surf_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
