"""add surfboards table

Revision ID: 85516576dd63
Revises: 6f571609f4f9
Create Date: 2026-01-28 13:26:52.889915

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '85516576dd63'
down_revision: Union[str, Sequence[str], None] = '6f571609f4f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surfboards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('length_ft', sa.Integer(), nullable=False),
    sa.Column('volume_liters', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surfboards_id'), 'surfboards', ['id'], unique=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=True)
    op.drop_index(op.f('ix_surfboards_id'), table_name='surfboards')
    op.drop_table('surfboards')
    # ### end Alembic commands ###
