"""add fiels surf_forecast_name to Spot and created new SurfForecast table

Revision ID: 85cd77af170c
Revises: bda0c001287d
Create Date: 2026-01-31 19:01:37.156882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85cd77af170c'
down_revision: Union[str, Sequence[str], None] = 'bda0c001287d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spots', sa.Column('surf_forecast_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spots', 'surf_forecast_name')
    # ### end Alembic commands ###
