"""updated SurfForecast table

Revision ID: 89fca42b6222
Revises: a425a8df3679
Create Date: 2026-02-01 13:59:45.081788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89fca42b6222'
down_revision: Union[str, Sequence[str], None] = 'a425a8df3679'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_forecasts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_forecasts', 'updated_at')
    # ### end Alembic commands ###
