"""init

Revision ID: 9561d6a3b591
Revises: 
Create Date: 2026-01-11 19:46:46.266513

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '9561d6a3b591'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
