"""updated SurfForecast table

Revision ID: a425a8df3679
Revises: 780920bd1444
Create Date: 2026-02-01 13:35:39.639726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a425a8df3679'
down_revision: Union[str, Sequence[str], None] = '780920bd1444'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_forecasts', sa.Column('wave_direction', sa.String(), nullable=True))
    op.add_column('surf_forecasts', sa.Column('energy', sa.Float(), nullable=True))
    op.add_column('surf_forecasts', sa.Column('wind_direction', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('surf_forecasts', 'wind_direction')
    op.drop_column('surf_forecasts', 'energy')
    op.drop_column('surf_forecasts', 'wave_direction')
    # ### end Alembic commands ###
