"""update surfboards table

Revision ID: bda0c001287d
Revises: 85516576dd63
Create Date: 2026-01-28 17:45:45.118039

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bda0c001287d'
down_revision: Union[str, Sequence[str], None] = '85516576dd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('surf_sessions', sa.Column('surfboard_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'surf_sessions', 'surfboards', ['surfboard_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surf_sessions', type_='foreignkey')
    op.drop_column('surf_sessions', 'surfboard_id')
    # ### end Alembic commands ###
