"""create sessions table

Revision ID: e964cec4554b
Revises: a6cc58e01faa
Create Date: 2026-01-16 16:39:00.465241

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e964cec4554b'
down_revision: Union[str, Sequence[str], None] = 'a6cc58e01faa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surf_sessions', 'created_at',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('surf_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
